import os
import requests
import json
import re
import shutil
from datetime import datetime

def get_rss_context():
    """Layer 1: Pull real-world threat intel with CDATA/Regex fixes"""
    feeds = [
        "https://feeds.feedburner.com/TheHackersNews",
        "https://krebsonsecurity.com/feed/"
    ]
    items = []
    for url in feeds:
        try:
            r = requests.get(url, timeout=8)
            # Handle both CDATA and standard XML titles
            titles = re.findall(r'<title>(?:<!\[CDATA\[)?(.*?)(?:\]\]>)?</title>', r.text, re.DOTALL)
            # Skip index 0 (feed name), take next 3 headlines
            items.extend([t.strip() for t in titles[1:4] if t.strip()])
        except Exception as e:
            print(f"RSS fetch failed for {url}: {e}")
    return " | ".join(items) if items else "Emerging Web3 Security Protocols 2026"

def get_groq_insight(report_text):
    """Layer 3: Critic Node — only runs if Gemini succeeded"""
    key = os.getenv('GROQ')
    if not key:
        return "Critic node offline: GROQ secret not set."
    try:
        headers = {"Authorization": f"Bearer {key}", "Content-Type": "application/json"}
        payload = {
            "model": "llama-3.3-70b-versatile",
            "messages": [{
                "role": "user",
                "content": (
                    f"Provide exactly 3 contrarian technical risks for this security report. "
                    f"Number each risk (1. 2. 3.) in one short aggressive expert sentence each:\n\n{report_text[:600]}"
                )
            }],
            "max_tokens": 300,
            "temperature": 0.7
        }
        r = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            json=payload, headers=headers, timeout=15
        )
        r.raise_for_status()
        return r.json()['choices'][0]['message']['content']
    except Exception as e:
        print(f"Groq critic failed: {e}")
        return "Skeptical oversight bypassed due to connection latency."

def send_telegram(title, summary):
    """Notify Telegram channel on successful update"""
    token = os.getenv("TELEGRAM_BOT_TOKEN")
    chat_id = os.getenv("TELEGRAM_CHANNEL_ID")
    if not token or not chat_id:
        return
    msg = (
        f"🧠 *AUTONOMOUS LAB UPDATE*\n\n"
        f"*{title}*\n\n{summary}\n\n"
        f"🔗 https://autonomous-portfolio-2026.live"
    )
    try:
        requests.post(
            f"https://api.telegram.org/bot{token}/sendMessage",
            data={"chat_id": chat_id, "text": msg, "parse_mode": "Markdown"},
            timeout=10
        )
    except Exception as e:
        print(f"Telegram notify failed: {e}")

def post_to_devto(title, summary, report_text, threat_level):
    """Publish each report to Dev.to for Google-indexed backlinks"""
    key = os.getenv("DEVTO_KEY")
    if not key:
        print("Dev.to key not set, skipping.")
        return
    body = (
        f"> 🔗 *Full interactive report: [autonomous-portfolio-2026.live](https://autonomous-portfolio-2026.live)*\n\n"
        f"## Executive Brief\n\n{summary}\n\n"
        f"## Technical Analysis\n\n{report_text}\n\n"
        f"---\n"
        f"*Threat Level: **{threat_level}** — Auto-generated by Multi-Agent AI Pipeline (Gemini + Groq + Tavily)*"
    )
    article = {
        "article": {
            "title": title,
            "body_markdown": body,
            "tags": ["security", "web3", "ai", "defi"],
            "published": True
        }
    }
    try:
        r = requests.post(
            "https://dev.to/api/articles",
            json=article,
            headers={"api-key": key, "Content-Type": "application/json"},
            timeout=15
        )
        r.raise_for_status()
        print(f"Dev.to article published: {r.json().get('url', 'no url')}")
    except Exception as e:
        print(f"Dev.to publish failed: {e}")

def write_sitemap_and_robots():
    """Generate sitemap.xml and robots.txt for Google indexing"""
    date_today = datetime.now().strftime("%Y-%m-%d")
    sitemap = f"""<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.2">
  <url>
    <loc>https://autonomous-portfolio-2026.live/</loc>
    <lastmod>{date_today}</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>"""
    robots = "User-agent: *\nAllow: /\nSitemap: https://autonomous-portfolio-2026.live/sitemap.xml\n"
    with open("sitemap.xml", "w") as f:
        f.write(sitemap)
    with open("robots.txt", "w") as f:
        f.write(robots)
    print("sitemap.xml and robots.txt updated.")

def run_production_agent():
    g_key = os.getenv("GEMINI")
    t_key = os.getenv("TAVILY")

    if not g_key:
        print("FATAL: GEMINI secret not set. Aborting.")
        return

    # --- LOAD OLD CONTENT (for archive + circuit breaker backup) ---
    old_content = ""
    if os.path.exists("index.html"):
        # Backup before any writes
        shutil.copy("index.html", "index.html.bak")
        with open("index.html", "r", encoding="utf-8") as f:
            old_content = f.read()

    # 1. RSS Intelligence Gathering
    rss_context = get_rss_context()
    print(f"RSS Context: {rss_context[:100]}...")

    # 2. Deep Research via Tavily
    research_context = rss_context
    if t_key:
        try:
            r = requests.post(
                "https://api.tavily.com/search",
                json={
                    "api_key": t_key,
                    "query": f"Technical deep dive: {rss_context} security implications 2026",
                    "max_results": 3
                },
                timeout=10
            )
            r.raise_for_status()
            results = r.json().get('results', [])
            if results:
                research_context = " ".join([
                    res.get('content', '') for res in results
                ])[:2000]
                print(f"Tavily research loaded: {len(research_context)} chars")
        except Exception as e:
            print(f"Tavily failed, using RSS context: {e}")

    # 3. Primary Brain — Gemini 1.5 Flash
    gemini_url = (
        f"https://generativelanguage.googleapis.com/v1beta/"
        f"models/gemini-1.5-flash:generateContent?key={g_key}"
    )
    prompt = f"""You are a Senior Security Architect writing for an elite 2026 research lab.
Context: {research_context}

Return ONLY a valid JSON object with NO extra text, NO markdown fences:
{{
  "title": "A sharp 4-6 word professional headline",
  "summary": "Two sentence executive brief that is direct and insightful",
  "report": "Four long detailed paragraphs of deep technical expert analysis separated by newlines",
  "threat_level": "Low or Medium or High or Critical",
  "audit_steps": ["Step 1 action", "Step 2 action", "Step 3 action"],
  "color": "#hexcolor"
}}"""

    data = None
    try:
        resp = requests.post(
            gemini_url,
            json={"contents": [{"parts": [{"text": prompt}]}]},
            timeout=25
        )
        resp.raise_for_status()
        raw_text = resp.json()['candidates'][0]['content']['parts'][0]['text']
        print(f"Gemini raw response length: {len(raw_text)}")

        # Robust JSON extraction — handles text before/after JSON block
        json_match = re.search(r'\{.*\}', raw_text, re.DOTALL)
        if not json_match:
            raise ValueError("No JSON object found in Gemini response")
        data = json.loads(json_match.group(0))
        print(f"Gemini succeeded: {data.get('title', 'no title')}")

    except Exception as e:
        print(f"CIRCUIT BREAKER TRIGGERED: Gemini failed — {e}")
        print("Aborting update. Old site remains live.")
        # Restore backup just in case
        if os.path.exists("index.html.bak"):
            shutil.copy("index.html.bak", "index.html")
        return  # Stop here — GitHub commit step will be a no-op

    # 4. Critic Node — Groq/Llama (only runs when Gemini succeeded)
    data['critic'] = get_groq_insight(data.get('report', ''))

    # 5. Build Archive History
    history_html = ""
    if "<!-- H_S -->" in old_content and "<!-- H_E -->" in old_content:
        history_html = old_content.split("<!-- H_S -->")[1].split("<!-- H_E -->")[0]

    date_str = datetime.now().strftime("%d %b %Y | %H:%M UTC")
    new_archive_entry = (
        f"<div class='mb-4 border-l border-white/5 pl-4 opacity-40 text-[10px]'>"
        f"<p class='mono'>{date_str}</p>"
        f"<p class='font-bold uppercase tracking-tighter'>{data.get('title', 'Update')}</p>"
        f"</div>"
    )
    # Keep archive under 3000 chars to avoid bloating the file
    final_history = (new_archive_entry + history_html)[:3000]

    # 6. UI Assembly
    color = data.get('color', '#3b82f6')
    threat = data.get('threat_level', 'Unknown')
    title = data.get('title', 'Intelligence Report')
    summary = data.get('summary', '')
    report = data.get('report', '').replace('\n', '<br><br>')
    critic = data.get('critic', '')
    audit_steps = data.get('audit_steps', ['System check'])
    steps_html = "".join([
        f'<p class="mb-2 uppercase italic">> {s}</p>' for s in audit_steps
    ])

    # Threat level badge color
    threat_colors = {
        "Critical": "#ef4444",
        "High": "#f97316",
        "Medium": "#eab308",
        "Low": "#22c55e"
    }
    threat_color = threat_colors.get(threat, "#94a3b8")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Autonomous Lab 2026 — {title}</title>
    <meta name="description" content="{summary}">
    <meta name="keywords" content="web3 security, DeFi, blockchain, AI research, {threat} threat, cybersecurity 2026">
    <meta name="robots" content="index, follow">
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{summary}">
    <meta property="og:url" content="https://autonomous-portfolio-2026.live">
    <meta property="og:type" content="article">
    <meta property="og:site_name" content="Autonomous Lab 2026">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="{title}">
    <meta name="twitter:description" content="{summary}">
    <link rel="canonical" href="https://autonomous-portfolio-2026.live/">
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;700;900&family=JetBrains+Mono:wght@400;700&display=swap" rel="stylesheet">
    <style>
        body {{ background: #020205; color: #f8fafc; font-family: 'Space Grotesk', sans-serif; }}
        .mono {{ font-family: 'JetBrains Mono', monospace; }}
        .glass {{
            background: rgba(15, 23, 42, 0.45);
            border: 1px solid rgba(255, 255, 255, 0.05);
            backdrop-filter: blur(16px);
            -webkit-backdrop-filter: blur(16px);
        }}
        #report {{ display: none; }}
        @keyframes pulse-dot {{ 0%, 100% {{ opacity: 1; }} 50% {{ opacity: 0.3; }} }}
        .live-dot {{ animation: pulse-dot 2s infinite; }}
    </style>
</head>
<body class="p-4 md:p-12 lg:p-16 min-h-screen">

    <!-- HEADER -->
    <header class="max-w-7xl mx-auto flex justify-between items-end mb-16 border-b border-white/5 pb-8">
        <div>
            <h1 class="text-3xl font-black tracking-tighter uppercase italic">
                AUTONOMOUS_<span style="color: {color}">LAB_2026</span>
            </h1>
            <p class="text-[10px] mono text-slate-500 uppercase tracking-widest italic mt-1">
                <span class="live-dot" style="color:{color}">●</span> Multi-Agent Intelligence Matrix — Live
            </p>
        </div>
        <div class="text-right text-[10px] mono font-bold uppercase">
            <p style="color: {threat_color}">Threat: {threat}</p>
            <p style="color: {color}" class="mt-1">{date_str}</p>
        </div>
    </header>

    <!-- MAIN GRID -->
    <main class="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-8">

        <!-- LEFT COLUMN -->
        <div class="lg:col-span-8 space-y-8">

            <!-- MAIN REPORT CARD -->
            <section class="glass p-8 md:p-10 rounded-[2.5rem] border-t-8 shadow-2xl" style="border-color: {color}">
                <p style="color: {color}" class="text-[10px] font-black uppercase tracking-[0.5em] mb-4 mono">
                    ● Intelligence_Briefing
                </p>
                <h2 class="text-4xl md:text-7xl font-black mb-6 leading-[0.85] tracking-tighter italic text-white">
                    {title}
                </h2>
                <p class="text-lg md:text-xl text-slate-400 mb-10 leading-snug italic">
                    "{summary}"
                </p>
                <button
                    onclick="document.getElementById('report').style.display='block'; this.style.display='none';"
                    class="bg-white text-black px-10 py-4 rounded-full text-[11px] font-black uppercase tracking-widest hover:opacity-80 transition shadow-xl">
                    Read Technical Deep-Dive ↓
                </button>
                <div id="report" class="mt-12 pt-12 border-t border-white/10 text-base md:text-lg text-slate-300 leading-relaxed space-y-6">
                    {report}
                </div>
            </section>

            <!-- CRITIC + AUDIT GRID -->
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div class="glass p-8 rounded-3xl border-l-4 border-red-500 shadow-xl shadow-red-500/5">
                    <h3 class="text-[10px] font-black text-red-500 uppercase mb-4 tracking-widest mono italic">
                        Skeptical_Critique // Groq
                    </h3>
                    <div class="text-xs text-slate-400 leading-relaxed italic whitespace-pre-line">
                        "{critic}"
                    </div>
                </div>
                <div class="glass p-8 rounded-3xl">
                    <h3 class="text-[10px] font-black text-slate-500 uppercase mb-4 tracking-widest mono">
                        Audit_Process_Log
                    </h3>
                    <div class="text-[10px] mono text-slate-500">
                        {steps_html}
                    </div>
                </div>
            </div>

        </div>

        <!-- RIGHT SIDEBAR -->
        <aside class="lg:col-span-4 space-y-8">

            <!-- ARCHIVE -->
            <div class="glass p-8 rounded-[2.5rem]">
                <h3 class="text-[10px] font-bold text-slate-500 uppercase mb-6 tracking-[0.3em] italic border-b border-white/5 pb-3">
                    Research_Archive
                </h3>
                <div class="mono overflow-hidden"><!-- H_S -->{final_history}<!-- H_E --></div>
            </div>

            <!-- OPERATIONAL STACK -->
            <div class="p-8 rounded-[2rem] text-[10px] mono bg-white/5 border border-white/5">
                <p class="mb-4 uppercase font-bold text-slate-400 tracking-[0.3em] underline decoration-slate-700">
                    Operational Stack:
                </p>
                <p class="mb-2 text-slate-600 italic">» NEWS: HackerNews_RSS / Krebs_Feed</p>
                <p class="mb-2 text-slate-600 italic">» RESEARCH: Tavily_Search_API</p>
                <p class="mb-2 text-slate-600 italic">» PRIMARY: Gemini_1.5_Flash</p>
                <p class="mb-2 text-slate-600 italic">» CRITIC: Llama_3.3_70b_Groq</p>
                <p class="mb-2 text-slate-600 italic">» NOTIFY: Telegram_Bot</p>
                <p class="mt-6 text-[8px] opacity-20 tracking-[0.3em] uppercase">
                    Decentralized Architecture // 2026
                </p>
            </div>

        </aside>
    </main>

    <!-- FOOTER -->
    <footer class="max-w-7xl mx-auto mt-16 pt-8 border-t border-white/5 text-[9px] mono text-slate-700 flex justify-between">
        <p>AUTO-GENERATED // AI AGENT PIPELINE // {date_str}</p>
        <p>autonomous-portfolio-2026.live</p>
    </footer>

</body>
</html>"""

    # --- WRITE WITH SAFETY ---
    try:
        with open("index.html", "w", encoding="utf-8") as f:
            f.write(html)
        print("index.html written successfully.")
    except Exception as e:
        print(f"File write failed: {e}. Restoring backup.")
        if os.path.exists("index.html.bak"):
            shutil.copy("index.html.bak", "index.html")
        return

    # Clean up backup on success
    if os.path.exists("index.html.bak"):
        os.remove("index.html.bak")

    # Update sitemap + robots.txt
    write_sitemap_and_robots()

    # Dev.to publish for SEO backlinks
    post_to_devto(title, summary, data.get('report', ''), threat)

    # Telegram notification
    send_telegram(title, summary)
    print("Production sync complete. Deployment proceeding.")

if __name__ == "__main__":
    run_production_agent()
